// Archivo: datos_simulados.dart

class DatosSimulados {
  static final Map<String, Map<String, dynamic>> estudiantes = {
    
    // ==========================================
    // 1. MANUEL ELIZONDO (Promedio 9.26 - SIN BECA)
    // ==========================================
    "362413591": {
      "nombre": "ELIZONDO SAUCEDA MANUEL",
      "matricula": "362413591",
      "carrera": "INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN E INNOVACIÓN DIGITAL",
      "estatus": "ACTIVO",
      "generacion": "40",
      "grupo": "1B ITIID",
      "ultimoCuatri": "6",
      "promedio": "9.26",
      "materiasAprobadas": "35",
      "creditosAprobados": "164.00",
      "materiasNoAcreditadas": "0",
      "nss": "26240544192",
      "horario": [{"clave": "EST_1", "asignatura": "ESTADÍA TSU", "aula": "-", "grupo": "1B ITIID-6", "profesor": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "cargaAcademica": [{"id": "127001", "clave": "EST_1", "asignatura": "ESTADÍA TSU", "tipoCurso": "ORDINARIO", "aula": "-", "grupo": "1B ITIID-6", "docente": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "historialCuatrimestres": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "tipo": "NI", "cuatri": "1", "materias": "7", "promedio": "9.29", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2025", "tipo": "RI", "cuatri": "2", "materias": "7", "promedio": "9.14", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2025", "tipo": "RI", "cuatri": "3", "materias": "7", "promedio": "9.14", "estatus": "A"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "tipo": "RI", "cuatri": "4", "materias": "7", "promedio": "9.14", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2026", "tipo": "RI", "cuatri": "5", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2026", "tipo": "RI", "cuatri": "6", "materias": "1", "promedio": "0.00", "estatus": "A"},
      ],
      "promediosBoleta": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "cuatri": "1", "promedio": "9.29"},
        {"periodo": "ENERO - ABRIL 2025", "cuatri": "2", "promedio": "9.14"},
        {"periodo": "MAYO - AGOSTO 2025", "cuatri": "3", "promedio": "9.14"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "cuatri": "4", "promedio": "9.14"},
        {"periodo": "ENERO - ABRIL 2026", "cuatri": "5", "promedio": "9.57"},
      ],
      "kardex": [
        {"clave": "E-CYHD-1", "materia": "COMUNICACIÓN Y HABILIDADES DIGITALES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DHU-1", "materia": "DESARROLLO HUMANO Y VALORES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FIS-1", "materia": "FÍSICA", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDP-1", "materia": "FUNDAMENTOS DE PROGRAMACIÓN", "cuatri": "1", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDR-1", "materia": "FUNDAMENTOS DE REDES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FMA-1", "materia": "FUNDAMENTOS MATEMÁTICOS", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING1-1", "materia": "INGLÉS I", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CDI-1", "materia": "CÁLCULO DIFERENCIAL", "cuatri": "2", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-CTER-1", "materia": "CONMUTACIÓN Y ENRUTAMIENTO DE REDES", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-HSMC-1", "materia": "HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING2-1", "materia": "INGLÉS II", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-PES-F-1", "materia": "PROBABILIDAD Y ESTADÍSTICA", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PRE-1", "materia": "PROGRAMACIÓN ESTRUCTURADA", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-SIOP-1", "materia": "SISTEMAS OPERATIVOS", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDD-1", "materia": "BASES DE DATOS", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CIN-1", "materia": "CÁLCULO INTEGRAL", "cuatri": "3", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DPTD-1", "materia": "DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING3-1", "materia": "INGLÉS III", "cuatri": "3", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-POAO-1", "materia": "PROGRAMACIÓN ORIENTADA A OBJETOS", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN1-1", "materia": "PROYECTO INTEGRADOR I", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-TCDS-1", "materia": "TÓPICOS DE CALIDAD PARA EL DISEÑO DE SOFTWARE", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AYDS-2", "materia": "ANÁLISIS Y DISEÑO DE SOFTWARE", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-APWB-2", "materia": "APLICACIONES WEB", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CVV-2", "materia": "CÁLCULO DE VARIAS VARIABLES", "cuatri": "4", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-DAPM-2", "materia": "DESARROLLO DE APLICACIONES MÓVILES", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ETD-2", "materia": "ESTRUCTURA DE DATOS", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-EPR-2", "materia": "ÉTICA PROFESIONAL", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING4-2", "materia": "INGLÉS IV", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AWOS-2", "materia": "APLICACIONES WEB ORIENTADAS A SERVICIOS", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDAV-2", "materia": "BASES DE DATOS AVANZADAS", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-EDI-2", "materia": "ECUACIONES DIFERENCIALES", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-EMDS-2", "materia": "ESTÁNDARES Y MÉTRICAS PARA EL DESARROLLO DE SOFTWARE", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING5-2", "materia": "INGLÉS V", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-LEAD-2", "materia": "LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN2-2", "materia": "PROYECTO INTEGRADOR II", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "EST_1", "materia": "ESTADÍA TSU", "cuatri": "6", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "O-BDEN-3", "materia": "BASES DE DATOS EN LA NUBE", "cuatri": "7", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ELTI-3", "materia": "ÉTICA Y LEGISLACIÓN EN TECNOLOGÍAS DE LA INFORMACIÓN", "cuatri": "7", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FPT-3", "materia": "FORMULACIÓN DE PROYECTOS DE TECNOLOGÍA", "cuatri": "7", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FIA-3", "materia": "FUNDAMENTOS DE INTELIGENCIA ARTIFICIAL", "cuatri": "7", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-HGE-3", "materia": "HABILIDADES GERENCIALES", "cuatri": "7", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING6-3", "materia": "INGLÉS VI", "cuatri": "7", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-SEIN-3", "materia": "SEGURIDAD INFORMÁTICA", "cuatri": "7", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ADS-3", "materia": "ADMINISTRACIÓN DE SERVIDORES", "cuatri": "8", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ELDG-3", "materia": "ELECTRÓNICA DIGITAL", "cuatri": "8", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-GPT-3", "materia": "GESTIÓN DE PROYECTOS DE TECNOLOGÍA", "cuatri": "8", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-IFOR-3", "materia": "INFORMÁTICA FORENSE", "cuatri": "8", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING7-3", "materia": "INGLÉS VII", "cuatri": "8", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "O-PMOA-3", "materia": "PROGRAMACIÓN MÓVIL AVANZADA", "cuatri": "8", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PPIA-3", "materia": "PROGRAMACIÓN PARA INTELIGENCIA ARTIFICIAL", "cuatri": "8", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-CIDA-3", "materia": "CIENCIA DE DATOS", "cuatri": "9", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-EPT-3", "materia": "EVALUACIÓN DE PROYECTOS DE TECNOLOGÍA", "cuatri": "9", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "O-FWDM-3", "materia": "FRAMEWORKS PARA EL DESARROLLO MULTIPLATAFORMA", "cuatri": "9", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING8-3", "materia": "INGLÉS VIII", "cuatri": "9", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-IDC-3", "materia": "INTERNET DE LAS COSAS", "cuatri": "9", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN3-3", "materia": "PROYECTO INTEGRADOR III", "cuatri": "9", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-TECD-3", "materia": "TECNOLOGÍAS DISRUPTIVAS", "cuatri": "9", "calificacion": "-", "tipo": "CURSO ORDINARIO"},
        {"clave": "EST_2", "materia": "ESTADÍA ING", "cuatri": "10", "calificacion": "-", "tipo": "CURSO ORDINARIO"}
      ],
      "becas": []
    },

    // ==========================================
    // 2. ENRIQUE TOSCANO (Promedio 9.45 - BECA 50%)
    // ==========================================
    "362413370": {
      "nombre": "GÓMEZ TOSCANO ENRIQUE GIBRÁN",
      "matricula": "362413370",
      "carrera": "INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN E INNOVACIÓN DIGITAL",
      "estatus": "ACTIVO",
      "generacion": "40",
      "grupo": "1B ITIID",
      "ultimoCuatri": "6",
      "promedio": "9.45",
      "materiasAprobadas": "35",
      "creditosAprobados": "164.00",
      "materiasNoAcreditadas": "0",
      "nss": "26240000001",
      "horario": [{"clave": "EST_1", "asignatura": "ESTADÍA TSU", "aula": "-", "grupo": "1B ITIID-6", "profesor": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "cargaAcademica": [{"id": "127002", "clave": "EST_1", "asignatura": "ESTADÍA TSU", "tipoCurso": "ORDINARIO", "aula": "-", "grupo": "1B ITIID-6", "docente": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "historialCuatrimestres": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "tipo": "NI", "cuatri": "1", "materias": "7", "promedio": "9.42", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2025", "tipo": "RI", "cuatri": "2", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2025", "tipo": "RI", "cuatri": "3", "materias": "7", "promedio": "9.42", "estatus": "A"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "tipo": "RI", "cuatri": "4", "materias": "7", "promedio": "9.42", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2026", "tipo": "RI", "cuatri": "5", "materias": "7", "promedio": "9.42", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2026", "tipo": "RI", "cuatri": "6", "materias": "1", "promedio": "0.00", "estatus": "A"},
      ],
      "promediosBoleta": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "cuatri": "1", "promedio": "9.42"},
        {"periodo": "ENERO - ABRIL 2025", "cuatri": "2", "promedio": "9.57"},
        {"periodo": "MAYO - AGOSTO 2025", "cuatri": "3", "promedio": "9.42"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "cuatri": "4", "promedio": "9.42"},
        {"periodo": "ENERO - ABRIL 2026", "cuatri": "5", "promedio": "9.42"},
      ],
      "kardex": [
        {"clave": "E-CYHD-1", "materia": "COMUNICACIÓN Y HABILIDADES DIGITALES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DHU-1", "materia": "DESARROLLO HUMANO Y VALORES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FIS-1", "materia": "FÍSICA", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDP-1", "materia": "FUNDAMENTOS DE PROGRAMACIÓN", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDR-1", "materia": "FUNDAMENTOS DE REDES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FMA-1", "materia": "FUNDAMENTOS MATEMÁTICOS", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING1-1", "materia": "INGLÉS I", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CDI-1", "materia": "CÁLCULO DIFERENCIAL", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-CTER-1", "materia": "CONMUTACIÓN Y ENRUTAMIENTO DE REDES", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-HSMC-1", "materia": "HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING2-1", "materia": "INGLÉS II", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-PES-F-1", "materia": "PROBABILIDAD Y ESTADÍSTICA", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PRE-1", "materia": "PROGRAMACIÓN ESTRUCTURADA", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-SIOP-1", "materia": "SISTEMAS OPERATIVOS", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDD-1", "materia": "BASES DE DATOS", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CIN-1", "materia": "CÁLCULO INTEGRAL", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DPTD-1", "materia": "DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING3-1", "materia": "INGLÉS III", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-POAO-1", "materia": "PROGRAMACIÓN ORIENTADA A OBJETOS", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN1-1", "materia": "PROYECTO INTEGRADOR I", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-TCDS-1", "materia": "TÓPICOS DE CALIDAD PARA EL DISEÑO DE SOFTWARE", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AYDS-2", "materia": "ANÁLISIS Y DISEÑO DE SOFTWARE", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-APWB-2", "materia": "APLICACIONES WEB", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CVV-2", "materia": "CÁLCULO DE VARIAS VARIABLES", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-DAPM-2", "materia": "DESARROLLO DE APLICACIONES MÓVILES", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ETD-2", "materia": "ESTRUCTURA DE DATOS", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-EPR-2", "materia": "ÉTICA PROFESIONAL", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING4-2", "materia": "INGLÉS IV", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AWOS-2", "materia": "APLICACIONES WEB ORIENTADAS A SERVICIOS", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDAV-2", "materia": "BASES DE DATOS AVANZADAS", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-EDI-2", "materia": "ECUACIONES DIFERENCIALES", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-EMDS-2", "materia": "ESTÁNDARES Y MÉTRICAS PARA EL DESARROLLO DE SOFTWARE", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING5-2", "materia": "INGLÉS V", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-LEAD-2", "materia": "LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN2-2", "materia": "PROYECTO INTEGRADOR II", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "EST_1", "materia": "ESTADÍA TSU", "cuatri": "6", "calificacion": "-", "tipo": "CURSO ORDINARIO"}
      ],
      "becas": [
        {"folio": "BEC-2026-1024", "estatus": "ACTIVA", "tipo": "Apoyo Académico", "porcentaje": "50%", "monto": "\$1,250.00", "cuatri": "6", "renovacion": "Automática", "obs": "Ninguna"}
      ]
    },

    // ==========================================
    // 3. JOSE ANGEL GANDARA (Promedio 9.10 - SIN BECA)
    // ==========================================
    "362413507": {
      "nombre": "GÁNDARA PÉREZ JOSE ÁNGEL",
      "matricula": "362413507",
      "carrera": "INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN E INNOVACIÓN DIGITAL",
      "estatus": "ACTIVO",
      "generacion": "40",
      "grupo": "1B ITIID",
      "ultimoCuatri": "6",
      "promedio": "9.10",
      "materiasAprobadas": "35",
      "creditosAprobados": "164.00",
      "materiasNoAcreditadas": "0",
      "nss": "26240000002",
      "horario": [{"clave": "EST_1", "asignatura": "ESTADÍA TSU", "aula": "-", "grupo": "1B ITIID-6", "profesor": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "cargaAcademica": [{"id": "127003", "clave": "EST_1", "asignatura": "ESTADÍA TSU", "tipoCurso": "ORDINARIO", "aula": "-", "grupo": "1B ITIID-6", "docente": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "historialCuatrimestres": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "tipo": "NI", "cuatri": "1", "materias": "7", "promedio": "9.14", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2025", "tipo": "RI", "cuatri": "2", "materias": "7", "promedio": "9.00", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2025", "tipo": "RI", "cuatri": "3", "materias": "7", "promedio": "9.14", "estatus": "A"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "tipo": "RI", "cuatri": "4", "materias": "7", "promedio": "9.00", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2026", "tipo": "RI", "cuatri": "5", "materias": "7", "promedio": "9.28", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2026", "tipo": "RI", "cuatri": "6", "materias": "1", "promedio": "0.00", "estatus": "A"},
      ],
      "promediosBoleta": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "cuatri": "1", "promedio": "9.14"},
        {"periodo": "ENERO - ABRIL 2025", "cuatri": "2", "promedio": "9.00"},
        {"periodo": "MAYO - AGOSTO 2025", "cuatri": "3", "promedio": "9.14"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "cuatri": "4", "promedio": "9.00"},
        {"periodo": "ENERO - ABRIL 2026", "cuatri": "5", "promedio": "9.28"},
      ],
      "kardex": [
        {"clave": "E-CYHD-1", "materia": "COMUNICACIÓN Y HABILIDADES DIGITALES", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DHU-1", "materia": "DESARROLLO HUMANO Y VALORES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FIS-1", "materia": "FÍSICA", "cuatri": "1", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDP-1", "materia": "FUNDAMENTOS DE PROGRAMACIÓN", "cuatri": "1", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDR-1", "materia": "FUNDAMENTOS DE REDES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FMA-1", "materia": "FUNDAMENTOS MATEMÁTICOS", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING1-1", "materia": "INGLÉS I", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CDI-1", "materia": "CÁLCULO DIFERENCIAL", "cuatri": "2", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-CTER-1", "materia": "CONMUTACIÓN Y ENRUTAMIENTO DE REDES", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-HSMC-1", "materia": "HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING2-1", "materia": "INGLÉS II", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-PES-F-1", "materia": "PROBABILIDAD Y ESTADÍSTICA", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PRE-1", "materia": "PROGRAMACIÓN ESTRUCTURADA", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-SIOP-1", "materia": "SISTEMAS OPERATIVOS", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDD-1", "materia": "BASES DE DATOS", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CIN-1", "materia": "CÁLCULO INTEGRAL", "cuatri": "3", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DPTD-1", "materia": "DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING3-1", "materia": "INGLÉS III", "cuatri": "3", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-POAO-1", "materia": "PROGRAMACIÓN ORIENTADA A OBJETOS", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN1-1", "materia": "PROYECTO INTEGRADOR I", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-TCDS-1", "materia": "TÓPICOS DE CALIDAD PARA EL DISEÑO DE SOFTWARE", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AYDS-2", "materia": "ANÁLISIS Y DISEÑO DE SOFTWARE", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-APWB-2", "materia": "APLICACIONES WEB", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CVV-2", "materia": "CÁLCULO DE VARIAS VARIABLES", "cuatri": "4", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-DAPM-2", "materia": "DESARROLLO DE APLICACIONES MÓVILES", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ETD-2", "materia": "ESTRUCTURA DE DATOS", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-EPR-2", "materia": "ÉTICA PROFESIONAL", "cuatri": "4", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING4-2", "materia": "INGLÉS IV", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AWOS-2", "materia": "APLICACIONES WEB ORIENTADAS A SERVICIOS", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDAV-2", "materia": "BASES DE DATOS AVANZADAS", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-EDI-2", "materia": "ECUACIONES DIFERENCIALES", "cuatri": "5", "calificacion": "8", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-EMDS-2", "materia": "ESTÁNDARES Y MÉTRICAS PARA EL DESARROLLO DE SOFTWARE", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING5-2", "materia": "INGLÉS V", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-LEAD-2", "materia": "LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN2-2", "materia": "PROYECTO INTEGRADOR II", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "EST_1", "materia": "ESTADÍA TSU", "cuatri": "6", "calificacion": "-", "tipo": "CURSO ORDINARIO"}
      ],
      "becas": []
    },

    // ==========================================
    // 4. DANIEL GARZA (Promedio 9.60 - BECA 50%)
    // ==========================================
    "362413445": {
      "nombre": "GARZA RODRÍGUEZ JOSECARLOS DANIEL",
      "matricula": "362413445",
      "carrera": "INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN E INNOVACIÓN DIGITAL",
      "estatus": "ACTIVO",
      "generacion": "40",
      "grupo": "1B ITIID",
      "ultimoCuatri": "6",
      "promedio": "9.60",
      "materiasAprobadas": "35",
      "creditosAprobados": "164.00",
      "materiasNoAcreditadas": "0",
      "nss": "26240000003",
      "horario": [{"clave": "EST_1", "asignatura": "ESTADÍA TSU", "aula": "-", "grupo": "1B ITIID-6", "profesor": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "cargaAcademica": [{"id": "127004", "clave": "EST_1", "asignatura": "ESTADÍA TSU", "tipoCurso": "ORDINARIO", "aula": "-", "grupo": "1B ITIID-6", "docente": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "historialCuatrimestres": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "tipo": "NI", "cuatri": "1", "materias": "7", "promedio": "9.71", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2025", "tipo": "RI", "cuatri": "2", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2025", "tipo": "RI", "cuatri": "3", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "tipo": "RI", "cuatri": "4", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2026", "tipo": "RI", "cuatri": "5", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2026", "tipo": "RI", "cuatri": "6", "materias": "1", "promedio": "0.00", "estatus": "A"},
      ],
      "promediosBoleta": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "cuatri": "1", "promedio": "9.71"},
        {"periodo": "ENERO - ABRIL 2025", "cuatri": "2", "promedio": "9.57"},
        {"periodo": "MAYO - AGOSTO 2025", "cuatri": "3", "promedio": "9.57"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "cuatri": "4", "promedio": "9.57"},
        {"periodo": "ENERO - ABRIL 2026", "cuatri": "5", "promedio": "9.57"},
      ],
      "kardex": [
        {"clave": "E-CYHD-1", "materia": "COMUNICACIÓN Y HABILIDADES DIGITALES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DHU-1", "materia": "DESARROLLO HUMANO Y VALORES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FIS-1", "materia": "FÍSICA", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDP-1", "materia": "FUNDAMENTOS DE PROGRAMACIÓN", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDR-1", "materia": "FUNDAMENTOS DE REDES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FMA-1", "materia": "FUNDAMENTOS MATEMÁTICOS", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING1-1", "materia": "INGLÉS I", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CDI-1", "materia": "CÁLCULO DIFERENCIAL", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-CTER-1", "materia": "CONMUTACIÓN Y ENRUTAMIENTO DE REDES", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-HSMC-1", "materia": "HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING2-1", "materia": "INGLÉS II", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-PES-F-1", "materia": "PROBABILIDAD Y ESTADÍSTICA", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PRE-1", "materia": "PROGRAMACIÓN ESTRUCTURADA", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-SIOP-1", "materia": "SISTEMAS OPERATIVOS", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDD-1", "materia": "BASES DE DATOS", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CIN-1", "materia": "CÁLCULO INTEGRAL", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DPTD-1", "materia": "DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING3-1", "materia": "INGLÉS III", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-POAO-1", "materia": "PROGRAMACIÓN ORIENTADA A OBJETOS", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN1-1", "materia": "PROYECTO INTEGRADOR I", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-TCDS-1", "materia": "TÓPICOS DE CALIDAD PARA EL DISEÑO DE SOFTWARE", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AYDS-2", "materia": "ANÁLISIS Y DISEÑO DE SOFTWARE", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-APWB-2", "materia": "APLICACIONES WEB", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CVV-2", "materia": "CÁLCULO DE VARIAS VARIABLES", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-DAPM-2", "materia": "DESARROLLO DE APLICACIONES MÓVILES", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ETD-2", "materia": "ESTRUCTURA DE DATOS", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-EPR-2", "materia": "ÉTICA PROFESIONAL", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING4-2", "materia": "INGLÉS IV", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AWOS-2", "materia": "APLICACIONES WEB ORIENTADAS A SERVICIOS", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDAV-2", "materia": "BASES DE DATOS AVANZADAS", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-EDI-2", "materia": "ECUACIONES DIFERENCIALES", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-EMDS-2", "materia": "ESTÁNDARES Y MÉTRICAS PARA EL DESARROLLO DE SOFTWARE", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING5-2", "materia": "INGLÉS V", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-LEAD-2", "materia": "LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN2-2", "materia": "PROYECTO INTEGRADOR II", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "EST_1", "materia": "ESTADÍA TSU", "cuatri": "6", "calificacion": "-", "tipo": "CURSO ORDINARIO"}
      ],
      "becas": [
        {"folio": "BEC-2026-1025", "estatus": "ACTIVA", "tipo": "Deportiva", "porcentaje": "50%", "monto": "\$1,250.00", "cuatri": "6", "renovacion": "Manual", "obs": "Entregar constancia"}
      ]
    },

    // ==========================================
    // 5. LESLIE RUIZ (Promedio 9.55 - BECA 50%)
    // ==========================================
    "362413431": {
      "nombre": "RUIZ TORRES LESLIE VANESSA",
      "matricula": "362413431",
      "carrera": "INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN E INNOVACIÓN DIGITAL",
      "estatus": "ACTIVO",
      "generacion": "40",
      "grupo": "1B ITIID",
      "ultimoCuatri": "6",
      "promedio": "9.55",
      "materiasAprobadas": "35",
      "creditosAprobados": "164.00",
      "materiasNoAcreditadas": "0",
      "nss": "26240000004",
      "horario": [{"clave": "EST_1", "asignatura": "ESTADÍA TSU", "aula": "-", "grupo": "1B ITIID-6", "profesor": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "cargaAcademica": [{"id": "127005", "clave": "EST_1", "asignatura": "ESTADÍA TSU", "tipoCurso": "ORDINARIO", "aula": "-", "grupo": "1B ITIID-6", "docente": "HERNANDEZ MARTINEZ YAARESI ARLEN"}],
      "historialCuatrimestres": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "tipo": "NI", "cuatri": "1", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2025", "tipo": "RI", "cuatri": "2", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2025", "tipo": "RI", "cuatri": "3", "materias": "7", "promedio": "9.42", "estatus": "A"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "tipo": "RI", "cuatri": "4", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "ENERO - ABRIL 2026", "tipo": "RI", "cuatri": "5", "materias": "7", "promedio": "9.57", "estatus": "A"},
        {"periodo": "MAYO - AGOSTO 2026", "tipo": "RI", "cuatri": "6", "materias": "1", "promedio": "0.00", "estatus": "A"},
      ],
      "promediosBoleta": [
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2024", "cuatri": "1", "promedio": "9.57"},
        {"periodo": "ENERO - ABRIL 2025", "cuatri": "2", "promedio": "9.57"},
        {"periodo": "MAYO - AGOSTO 2025", "cuatri": "3", "promedio": "9.42"},
        {"periodo": "SEPTIEMBRE - DICIEMBRE 2025", "cuatri": "4", "promedio": "9.57"},
        {"periodo": "ENERO - ABRIL 2026", "cuatri": "5", "promedio": "9.57"},
      ],
      "kardex": [
        {"clave": "E-CYHD-1", "materia": "COMUNICACIÓN Y HABILIDADES DIGITALES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DHU-1", "materia": "DESARROLLO HUMANO Y VALORES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FIS-1", "materia": "FÍSICA", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDP-1", "materia": "FUNDAMENTOS DE PROGRAMACIÓN", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-FDR-1", "materia": "FUNDAMENTOS DE REDES", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-FMA-1", "materia": "FUNDAMENTOS MATEMÁTICOS", "cuatri": "1", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING1-1", "materia": "INGLÉS I", "cuatri": "1", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CDI-1", "materia": "CÁLCULO DIFERENCIAL", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-CTER-1", "materia": "CONMUTACIÓN Y ENRUTAMIENTO DE REDES", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-HSMC-1", "materia": "HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING2-1", "materia": "INGLÉS II", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-PES-F-1", "materia": "PROBABILIDAD Y ESTADÍSTICA", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PRE-1", "materia": "PROGRAMACIÓN ESTRUCTURADA", "cuatri": "2", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-SIOP-1", "materia": "SISTEMAS OPERATIVOS", "cuatri": "2", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDD-1", "materia": "BASES DE DATOS", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CIN-1", "materia": "CÁLCULO INTEGRAL", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-DPTD-1", "materia": "DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING3-1", "materia": "INGLÉS III", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-POAO-1", "materia": "PROGRAMACIÓN ORIENTADA A OBJETOS", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN1-1", "materia": "PROYECTO INTEGRADOR I", "cuatri": "3", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-TCDS-1", "materia": "TÓPICOS DE CALIDAD PARA EL DISEÑO DE SOFTWARE", "cuatri": "3", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AYDS-2", "materia": "ANÁLISIS Y DISEÑO DE SOFTWARE", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-APWB-2", "materia": "APLICACIONES WEB", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-CVV-2", "materia": "CÁLCULO DE VARIAS VARIABLES", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-DAPM-2", "materia": "DESARROLLO DE APLICACIONES MÓVILES", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-ETD-2", "materia": "ESTRUCTURA DE DATOS", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-EPR-2", "materia": "ÉTICA PROFESIONAL", "cuatri": "4", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING4-2", "materia": "INGLÉS IV", "cuatri": "4", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-AWOS-2", "materia": "APLICACIONES WEB ORIENTADAS A SERVICIOS", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-BDAV-2", "materia": "BASES DE DATOS AVANZADAS", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-EDI-2", "materia": "ECUACIONES DIFERENCIALES", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-EMDS-2", "materia": "ESTÁNDARES Y MÉTRICAS PARA EL DESARROLLO DE SOFTWARE", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "B-ING5-2", "materia": "INGLÉS V", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "T-LEAD-2", "materia": "LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO", "cuatri": "5", "calificacion": "10", "tipo": "CURSO ORDINARIO"},
        {"clave": "E-PIN2-2", "materia": "PROYECTO INTEGRADOR II", "cuatri": "5", "calificacion": "9", "tipo": "CURSO ORDINARIO"},
        {"clave": "EST_1", "materia": "ESTADÍA TSU", "cuatri": "6", "calificacion": "-", "tipo": "CURSO ORDINARIO"}
      ],
      "becas": [
        {"folio": "BEC-2026-1026", "estatus": "ACTIVA", "tipo": "Apoyo Académico", "porcentaje": "50%", "monto": "\$1,250.00", "cuatri": "6", "renovacion": "Automática", "obs": "Ninguna"}
      ]
    }
  };
}